FROM python:3.11.1-alpine

# Create and enable venv
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip

WORKDIR /app/

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ./utils.py .
COPY ./sensor.py .

ENTRYPOINT [ "python", "sensor.py" ]
