services:
  # This is the knowledge directory, facilitating discovery between different
  # runtimes. It exposes its service over port 8282.
  knowledge-directory:
    image: ghcr.io/tno/knowledge-engine/knowledge-directory:1.2.4

  # These services are seperate Knowledge Engine runtime, which can host
  # multiple smart connectors. Note that the REST API port is a DIFFERENT port
  # number than the ones configured below. It is still the default 8280.
  runtime-1:
    image: ghcr.io/tno/knowledge-engine/smart-connector:1.2.4
    environment: 
      KE_RUNTIME_PORT: 8081 # The port that the KE uses to listen for inter-KE-runtime communication.
      KE_RUNTIME_EXPOSED_URL: http://runtime-1:8081 # The URL where the runtime is available for inter-runtime communication from the outside.
      KD_URL: http://knowledge-directory:8282
  runtime-2:
    image: ghcr.io/tno/knowledge-engine/smart-connector:1.2.4
    environment: 
      KE_RUNTIME_PORT: 8081
      KE_RUNTIME_EXPOSED_URL: http://runtime-2:8081
      KD_URL: http://knowledge-directory:8282
  runtime-3:
    image: ghcr.io/tno/knowledge-engine/smart-connector:1.2.4
    environment: 
      KE_RUNTIME_PORT: 8081
      KE_RUNTIME_EXPOSED_URL: http://runtime-3:8081
      KD_URL: http://knowledge-directory:8282
  
  # These Knowledge Bases use the different runtimes, and exchange data with eachother.
  kb1:
    build: ../common/asking_kb
    environment:
      KE_URL: http://runtime-1:8280/rest
      KB_ID: http://example.org/kb1
      PREFIXES: |
        {
          "ex": "http://example.org/"
        }
      GRAPH_PATTERN: |
        ?a ex:relatedTo ?b .
  kb2:
    build: ../common/answering_kb
    environment:
      KE_URL: http://runtime-2:8280/rest
      KB_ID: http://example.org/kb2
      PREFIXES: |
        {
          "ex": "http://example.org/"
        }
      GRAPH_PATTERN: |
        ?a ex:relatedTo ?b .
      KB_DATA: |
        [
          {
            "a": "<http://example.org/Math>",
            "b": "<http://example.org/Science>"
          },
          {
            "a": "<http://example.org/Books>",
            "b": "<http://example.org/Magazines>"
          }
        ]
  kb3:
    build: ../common/answering_kb
    environment:
      KE_URL: http://runtime-3:8280/rest
      KB_ID: http://example.org/kb3
      PREFIXES: |
        {
          "ex": "http://example.org/"
        }
      GRAPH_PATTERN: |
        ?a ex:relatedTo ?b .
      KB_DATA: |
        [
          {
            "a": "<http://example.org/Music>",
            "b": "<http://example.org/Songs>"
          },
          {
            "a": "<http://example.org/Red>",
            "b": "<http://example.org/Blue>"
          }
        ]
